/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GammyGrams } from "./GammyGrams";
export * as factories from "./factories";
export { GammyGrams__factory } from "./factories/GammyGrams__factory";
